name: equity_ware_app_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  location: 
    ^5.0.3
  flutter_map:
    ^5.0.0
  latlong2:
    ^0.9.0
  geolocator: 
    ^9.0.0
  flutter_blue:
    ^0.8.0
  intl: ^0.19.0
  http: ^1.2.1
  flutter_local_notifications: ^17.2.1+2
  flutter_background_service: ^5.0.6
  shared_preferences: ^2.2.3
  flutter_dialogs: ^3.0.0
  web_socket_channel: ^3.0.1
  syncfusion_flutter_charts: ^27.2.2

dev_dependencies:
  #flutter_test:
    # sdk: Flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
